CREATE TYPE "public"."loan_status" AS ENUM('NONE', 'PROPOSED', 'ACTIVE', 'REPAID', 'DEFAULTED', 'CANCELLED');--> statement-breakpoint
CREATE TYPE "public"."stablecoin" AS ENUM('USDC', 'USDT');--> statement-breakpoint
CREATE TABLE "qbytic_account" (
	"user_id" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"provider_account_id" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "qbytic_account_provider_provider_account_id_pk" PRIMARY KEY("provider","provider_account_id")
);
--> statement-breakpoint
CREATE TABLE "qbytic_loan" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY (sequence name "qbytic_loan_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"borrower_id" varchar(255) NOT NULL,
	"lender_id" varchar(255),
	"collateral_amount" numeric(38, 18),
	"principal_amount" numeric(38, 18) NOT NULL,
	"outstanding_debt" numeric(38, 18),
	"interest_rate" integer,
	"monthly_payment" numeric(38, 18),
	"duration" bigint NOT NULL,
	"proposal_time" timestamp with time zone,
	"start_time" timestamp with time zone,
	"last_payment_time" timestamp with time zone,
	"proposal_expiration" timestamp with time zone,
	"credit_score" integer,
	"stablecoin" "stablecoin" NOT NULL,
	"loan_status" "loan_status" DEFAULT 'PROPOSED' NOT NULL,
	"total_repaid" numeric(38, 18) DEFAULT '0',
	"liquidated_amount" numeric(38, 18) DEFAULT '0',
	"collateral_deposited" boolean DEFAULT false,
	"collateral_holder" varchar(255),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "qbytic_session" (
	"session_token" varchar(255) PRIMARY KEY NOT NULL,
	"user_id" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "qbytic_user" (
	"id" varchar(255),
	"name" varchar(255),
	"username" varchar(255),
	"email" varchar(255) NOT NULL,
	"email_verified" timestamp with time zone,
	"credit_score" integer,
	"image" varchar(255),
	CONSTRAINT "qbytic_user_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "qbytic_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "qbytic_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "qbytic_account" ADD CONSTRAINT "qbytic_account_user_id_qbytic_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."qbytic_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qbytic_loan" ADD CONSTRAINT "qbytic_loan_borrower_id_qbytic_user_id_fk" FOREIGN KEY ("borrower_id") REFERENCES "public"."qbytic_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qbytic_loan" ADD CONSTRAINT "qbytic_loan_lender_id_qbytic_user_id_fk" FOREIGN KEY ("lender_id") REFERENCES "public"."qbytic_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qbytic_session" ADD CONSTRAINT "qbytic_session_user_id_qbytic_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."qbytic_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "account_user_id_idx" ON "qbytic_account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "loan_borrower_idx" ON "qbytic_loan" USING btree ("borrower_id");--> statement-breakpoint
CREATE INDEX "loan_lender_idx" ON "qbytic_loan" USING btree ("lender_id");--> statement-breakpoint
CREATE INDEX "loan_status_idx" ON "qbytic_loan" USING btree ("loan_status");--> statement-breakpoint
CREATE INDEX "session_user_id_idx" ON "qbytic_session" USING btree ("user_id");