CREATE TYPE "public"."loan_status" AS ENUM('NONE', 'PROPOSED', 'ACTIVE', 'REPAID', 'DEFAULTED', 'CANCELLED');--> statement-breakpoint
CREATE TYPE "public"."stablecoin" AS ENUM('USDC', 'USDT');--> statement-breakpoint
CREATE TABLE "qbytic_loan" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "qbytic_loan_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"borrower_id" varchar(255) NOT NULL,
	"lender_id" varchar(255),
	"collateral_amount" numeric(38, 18),
	"principal_amount" numeric(38, 18) NOT NULL,
	"outstanding_debt" numeric(38, 18),
	"interest_rate" integer,
	"monthly_payment" numeric(38, 18),
	"duration" bigint NOT NULL,
	"proposal_time" timestamp with time zone,
	"start_time" timestamp with time zone,
	"last_payment_time" timestamp with time zone,
	"proposal_expiration" timestamp with time zone,
	"credit_score" integer,
	"stablecoin" "stablecoin" NOT NULL,
	"loan_status" "loan_status" DEFAULT 'PROPOSED' NOT NULL,
	"total_repaid" numeric(38, 18) DEFAULT '0',
	"liquidated_amount" numeric(38, 18) DEFAULT '0',
	"collateral_deposited" boolean DEFAULT false,
	"collateral_holder" varchar(255),
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "qbytic_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(255) NOT NULL,
	"credit_score" integer,
	"image" varchar(255)
);
--> statement-breakpoint
ALTER TABLE "qbytic_loan" ADD CONSTRAINT "qbytic_loan_borrower_id_qbytic_user_id_fk" FOREIGN KEY ("borrower_id") REFERENCES "public"."qbytic_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "qbytic_loan" ADD CONSTRAINT "qbytic_loan_lender_id_qbytic_user_id_fk" FOREIGN KEY ("lender_id") REFERENCES "public"."qbytic_user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "loan_borrower_idx" ON "qbytic_loan" USING btree ("borrower_id");--> statement-breakpoint
CREATE INDEX "loan_lender_idx" ON "qbytic_loan" USING btree ("lender_id");--> statement-breakpoint
CREATE INDEX "loan_status_idx" ON "qbytic_loan" USING btree ("loan_status");