ALTER TABLE "qbytic_account" ALTER COLUMN "user_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "qbytic_loan" ALTER COLUMN "borrower_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "qbytic_loan" ALTER COLUMN "lender_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "qbytic_session" ALTER COLUMN "user_id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "qbytic_user" ADD PRIMARY KEY ("id");--> statement-breakpoint
ALTER TABLE "qbytic_user" ALTER COLUMN "id" SET DATA TYPE integer;--> statement-breakpoint
ALTER TABLE "qbytic_user" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "qbytic_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);